create table if not exists public.purchases (
  id bigint generated by default as identity primary key,
  purchase_date date not null,
  store_name text not null,
  total_amount numeric(12, 2) not null,
  category text not null,
  items_notes text,
  rewards_earned numeric(12, 2) not null default 0,
  created_at timestamptz not null default now()
);

alter table public.purchases enable row level security;

-- No public policies are needed when writes go through the private Node API
-- using SUPABASE_SERVICE_ROLE_KEY. Keep that key out of browser VITE_* env vars.
create index if not exists purchases_created_at_idx on public.purchases (created_at desc);
create index if not exists purchases_purchase_date_idx on public.purchases (purchase_date desc);

create table if not exists public.receipt_folders (
  id bigint generated by default as identity primary key,
  name text not null,
  retailer text not null,
  created_at timestamptz not null default now()
);

alter table public.receipt_folders enable row level security;

create unique index if not exists receipt_folders_name_lower_idx on public.receipt_folders (lower(name));
create index if not exists receipt_folders_retailer_idx on public.receipt_folders (retailer);

create table if not exists public.receipts (
  id bigint generated by default as identity primary key,
  receipt_date date not null,
  retailer text not null,
  folder_id bigint references public.receipt_folders(id) on delete set null,
  folder_name text not null,
  total_amount numeric(12, 2),
  receipt_url text,
  receipt_file_name text,
  receipt_content_type text,
  notes text,
  created_at timestamptz not null default now()
);

alter table public.receipts add column if not exists receipt_file_name text;
alter table public.receipts add column if not exists receipt_content_type text;
alter table public.receipts enable row level security;

create index if not exists receipts_created_at_idx on public.receipts (created_at desc);
create index if not exists receipts_receipt_date_idx on public.receipts (receipt_date desc);
create index if not exists receipts_retailer_idx on public.receipts (retailer);

create table if not exists public.costco_orders (
  id bigint generated by default as identity primary key,
  source_message_id text not null,
  received_at timestamptz,
  account_email text,
  order_number_display text,
  order_number_last4 text,
  order_date_text text,
  membership_number_display text,
  membership_number_last4 text,
  item_name text,
  item_number text,
  quantity text,
  unit_price_amount numeric(12, 2),
  subtotal_amount numeric(12, 2),
  shipping_handling_amount numeric(12, 2),
  tax_amount numeric(12, 2),
  total_amount numeric(12, 2),
  status text,
  next_action text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.costco_orders add column if not exists subtotal_amount numeric(12, 2);
alter table public.costco_orders add column if not exists shipping_handling_amount numeric(12, 2);
alter table public.costco_orders add column if not exists tax_amount numeric(12, 2);
alter table public.costco_orders enable row level security;

create unique index if not exists costco_orders_source_message_id_idx on public.costco_orders (source_message_id);
create index if not exists costco_orders_received_at_idx on public.costco_orders (received_at desc);
create index if not exists costco_orders_order_last4_idx on public.costco_orders (order_number_last4);

create table if not exists public.us_mint_orders (
  id bigint generated by default as identity primary key,
  source_message_id text not null,
  received_at timestamptz,
  account_email text,
  order_number text,
  order_date_text text,
  item_name text,
  item_description text,
  unit_of_measure text,
  quantity text,
  subtotal_amount numeric(12, 2),
  total_amount numeric(12, 2),
  status text,
  next_action text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.us_mint_orders add column if not exists item_description text;
alter table public.us_mint_orders add column if not exists unit_of_measure text;
alter table public.us_mint_orders enable row level security;

create unique index if not exists us_mint_orders_source_message_id_idx on public.us_mint_orders (source_message_id);
create index if not exists us_mint_orders_received_at_idx on public.us_mint_orders (received_at desc);
create index if not exists us_mint_orders_order_number_idx on public.us_mint_orders (order_number);
