create table if not exists public.purchases (
  id bigint generated by default as identity primary key,
  purchase_date date not null,
  store_name text not null,
  total_amount numeric(12, 2) not null,
  category text not null,
  items_notes text,
  rewards_earned numeric(12, 2) not null default 0,
  created_at timestamptz not null default now()
);

alter table public.purchases enable row level security;

-- No public policies are needed when writes go through the private Node API
-- using SUPABASE_SERVICE_ROLE_KEY. Keep that key out of browser VITE_* env vars.
create index if not exists purchases_created_at_idx on public.purchases (created_at desc);
create index if not exists purchases_purchase_date_idx on public.purchases (purchase_date desc);

create table if not exists public.receipt_folders (
  id bigint generated by default as identity primary key,
  name text not null,
  retailer text not null,
  created_at timestamptz not null default now()
);

alter table public.receipt_folders enable row level security;

create unique index if not exists receipt_folders_name_lower_idx on public.receipt_folders (lower(name));
create index if not exists receipt_folders_retailer_idx on public.receipt_folders (retailer);

create table if not exists public.receipts (
  id bigint generated by default as identity primary key,
  receipt_date date not null,
  retailer text not null,
  folder_id bigint references public.receipt_folders(id) on delete set null,
  folder_name text not null,
  total_amount numeric(12, 2),
  receipt_url text,
  receipt_file_name text,
  receipt_content_type text,
  notes text,
  created_at timestamptz not null default now()
);

alter table public.receipts add column if not exists receipt_file_name text;
alter table public.receipts add column if not exists receipt_content_type text;
alter table public.receipts enable row level security;

create index if not exists receipts_created_at_idx on public.receipts (created_at desc);
create index if not exists receipts_receipt_date_idx on public.receipts (receipt_date desc);
create index if not exists receipts_retailer_idx on public.receipts (retailer);

create table if not exists public.auth_users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  email text,
  name text not null,
  password_hash text not null,
  two_factor_enabled boolean not null default false,
  two_factor_secret text,
  role text not null default 'user',
  password_reset_token_hash text,
  password_reset_expires_at timestamptz,
  password_reset_requested_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.auth_users add column if not exists email text;
alter table public.auth_users add column if not exists password_reset_token_hash text;
alter table public.auth_users add column if not exists password_reset_expires_at timestamptz;
alter table public.auth_users add column if not exists password_reset_requested_at timestamptz;
alter table public.auth_users enable row level security;

create unique index if not exists auth_users_email_lower_idx
  on public.auth_users (lower(email))
  where email is not null and email <> '';
create index if not exists auth_users_password_reset_token_hash_idx
  on public.auth_users (password_reset_token_hash)
  where password_reset_token_hash is not null;
